# This file is automatically generated by pyo3_stub_gen

import typing

from nautilus_trader import model
from nautilus_trader.config import (
    InstrumentProviderConfig,
    LiveDataClientConfig,
    LiveExecClientConfig,
    NautilusConfig,
)
from nautilus_trader.live.data_client import LiveMarketDataClient
from nautilus_trader.live.execution_client import LiveExecutionClient
from nautilus_trader.live.factories import LiveDataClientFactory
from nautilus_trader.live.factories import LiveExecClientFactory
from nautilus_trader.model.identifiers import ClientId
from nautilus_trader.model.identifiers import Venue
from nautilus_trader.model.instruments.base import InstrumentProvider

__all__ = [
    "TINVEST",
    "TINVEST_CLIENT_ID",
    "TINVEST_VENUE",
    "TInvestClientConfig",
    "TInvestDataClient",
    "TInvestDataClientConfig",
    "TInvestExecClientConfig",
    "TInvestExecutionClient",
    "TInvestInstrumentProvider",
    "TInvestInstrumentProviderConfig",
    "TInvestLiveDataClientFactory",
    "TInvestLiveExecClientFactory",
    "TInvestMarketDataStream",
    "TInvestOrderStateStream",
    "TInvestPortfolioStream",
    "TInvestPositionsStream",
]

TINVEST: str
TINVEST_CLIENT_ID: model.ClientId
TINVEST_VENUE: model.Venue

@typing.final
class TInvestClientConfig(NautilusConfig):
    def __hash__(self) -> int: ...

@typing.final
class TInvestDataClientConfig(LiveDataClientConfig):
    pass

@typing.final
class TInvestExecClientConfig(LiveExecClientConfig):
    pass

@typing.final
class TInvestInstrumentProviderConfig(InstrumentProviderConfig):
    pass

class TInvestDataClient(LiveMarketDataClient):
    pass

class TInvestExecutionClient(LiveExecutionClient):
    pass

class TInvestInstrumentProvider(InstrumentProvider):
    pass

class TInvestLiveDataClientFactory(LiveDataClientFactory):
    pass

class TInvestLiveExecClientFactory(LiveExecClientFactory):
    pass

class TInvestMarketDataStream:
    pass

class TInvestOrderStateStream:
    pass

class TInvestPortfolioStream:
    pass

class TInvestPositionsStream:
    pass
