# This file is automatically generated by pyo3_stub_gen

import typing

from nautilus_trader import model
from nautilus_trader.config import InstrumentProviderConfig
from nautilus_trader.config import LiveDataClientConfig
from nautilus_trader.config import LiveExecClientConfig
from nautilus_trader.config import NautilusConfig
from nautilus_trader.live.data_client import LiveMarketDataClient
from nautilus_trader.live.execution_client import LiveExecutionClient
from nautilus_trader.live.factories import LiveDataClientFactory
from nautilus_trader.live.factories import LiveExecClientFactory
from nautilus_trader.model.instruments.base import InstrumentProvider

__all__ = [
    "TINVEST",
    "TINVEST_CLIENT_ID",
    "TINVEST_VENUE",
    "TInvestClientConfig",
    "TInvestDataClient",
    "TInvestDataClientConfig",
    "TInvestExecClientConfig",
    "TInvestExecutionClient",
    "TInvestInstrumentProvider",
    "TInvestInstrumentProviderConfig",
    "TInvestLiveDataClientFactory",
    "TInvestLiveExecClientFactory",
    "TInvestMarketDataStream",
    "TInvestOrderStateStream",
    "TInvestPortfolioStream",
    "TInvestPositionsStream",
]

TINVEST: str
TINVEST_CLIENT_ID: model.ClientId
TINVEST_VENUE: model.Venue

@typing.final
class TInvestClientConfig(NautilusConfig):
    def __hash__(self) -> int: ...

@typing.final
class TInvestDataClientConfig(LiveDataClientConfig):
    ...

@typing.final
class TInvestExecClientConfig(LiveExecClientConfig):
    ...

@typing.final
class TInvestInstrumentProviderConfig(InstrumentProviderConfig):
    ...

class TInvestDataClient(LiveMarketDataClient):
    ...

class TInvestExecutionClient(LiveExecutionClient):
    ...

class TInvestInstrumentProvider(InstrumentProvider):
    ...

class TInvestLiveDataClientFactory(LiveDataClientFactory):
    ...

class TInvestLiveExecClientFactory(LiveExecClientFactory):
    ...

class TInvestMarketDataStream:
    ...

class TInvestOrderStateStream:
    ...

class TInvestPortfolioStream:
    ...

class TInvestPositionsStream:
    ...
