name: Sync Fork

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v7

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.3
        with:
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: develop
          upstream_repo_owner: nautechsystems
          upstream_repo: nautilus_trader
          upstream_branch: develop
          test_mode: false
